version: '2'
services:
  mongod:
    container_name: cltfevents_mongodb
    image: cltfevents_mongodb
    build: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always

  elasticsearch:
    container_name: cltfevents_elasticsearch
    image: cltfevents_elasticsearch
    build: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
#  nginx:
#    container_name: cltfevents_nginx
#    image: cltfevents_nginx
#    build: nginx
#    ports:
#      - "80:80"
#    restart: always
#    environment:
##      - HTPASSWD=$'foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.\ntest:$apr1$LKkW8P4Y$P1X/r2YyaexhVL1LzZAQm.'
#      - FORWARD_PORT=8080
#      - FORWARD_HOST=192.168.1.208

#  backup:
#    container_name: vcpuicms_backup
#    image: vcpuicms_backup
#    volumes:
#      - backup:/backup
#    volumes_from:
#      - mariadbdata
#      - wwwdata
#    environment:
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASS=${MYSQL_PASS}
#      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
#      - MYSQL_HOST=${MYSQL_HOST}

volumes:
  mongodb:
  elasticsearch:
#  backup:

networks: {}
