version: '2'
services:
  mongod:
    container_name: cltfevents_mongodb
    image: cltfevents_mongodb
    build: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always

  elasticsearch:
    container_name: cltfevents_elasticsearch
    image: cltfevents_elasticsearch
    build: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  nodejs:
    container_name: cltfevents_nodejs
    image: cltfevents_nodejs
    build: server
    volumes:
      - .:/home/cltfevents
    ports:
      - "8080:8080"
    restart: always

  maildev:
    container_name: cltfevents_maildev
    image: djfarrelly/maildev
    ports:
      - "1025:25"
      - "1080:80"
    restart: always

  nginx:
    container_name: cltfevents_nginx
    image: cltfevents_nginx
    build: nginx
    ports:
      - "80:80"
    environment:
      - BASIC_AUTH_USERNAME=capstone
      - BASIC_AUTH_PASSWORD=wgu
      - PROXY_PASS=http://nodejs:8080/
    restart: always



#  backup:
#    container_name: vcpuicms_backup
#    image: vcpuicms_backup
#    volumes:
#      - backup:/backup
#    volumes_from:
#      - mariadbdata
#      - wwwdata
#    environment:
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASS=${MYSQL_PASS}
#      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
#      - MYSQL_HOST=${MYSQL_HOST}

volumes:
  mongodb:
  elasticsearch:
  nodejs:
#  backup:

networks: {}
